function ereg_fanout_dual(P)
%EREG_FANOUT_DUAL Base-workspace fan-out for the dual model. Branch-specific
% plant parameters carry _fu/_ox suffixes (the builder renames the chart
% parameter symbols to match).
vars = struct( ...
    'Ts_sim', P.Ts_sim, 'Ts_ctrl', P.Ts_ctrl, 'Sim_Duration', P.Sim_Duration, ...
    'V_1', P.V_1, 'V_2', P.V_2, 'T_0_N2', P.T_0_N2, 'rho_1_0', P.rho_1_0, ...
    'gamma_N2', P.gamma_N2, 'R_N2', P.R_N2, 'Tst', P.Tst, 'rhost', P.rhost, ...
    'Pst', P.Pst, 'Kv_1_max', P.Kv_1_max, 'm_1_0', P.m_1_0, ...
    'backlash_width', P.backlash_width, 'backlash_init', P.backlash_init, ...
    'ctrl_params', P.ctrl, 'cv_N2', P.cv_N2, 'cp_N2', P.cp_N2, ...
    'n2o_lut', P.n2o_lut, ...
    'rho_L_fu', P.fu.rho_L, 'Cd_3_fu', P.fu.Cd_3, 'A_3_fu', P.fu.A_3, ...
    'K_v_4_fu', P.fu.K_v_4, 'm_2_0_fu', P.fu.m_2_0, 'm_3_0_fu', P.fu.m_3_0, ...
    'Cd_3_ox', P.ox.Cd_3, 'A_3_ox', P.ox.A_3, 'K_v_4_ox', P.ox.K_v_4, ...
    'm_N2O_0', P.ox.ic.m_N2O, 'm_N2tank_0', P.ox.ic.m_N2, 'U_n2o_0', P.ox.ic.U);
fn = fieldnames(vars);
for i = 1:numel(fn)
    assignin('base', fn{i}, vars.(fn{i}));
end

% per-branch command sequences (reuses the clean-mode sequence builder)
for br = {'fu', 'ox'}
    Q = struct('compat_v1', false, 'Sim_Duration', P.Sim_Duration, ...
        'sequence', {P.(br{1}).sequence}, 'fluid', struct('name', br{1}));
    seq = ereg_make_sequence(Q);
    assignin('base', ['mode_cmd_' br{1} '_ts'], seq.mode_cmd_ts);
    assignin('base', ['P_set_cmd_' br{1} '_ts'], seq.P_set_cmd_ts);
    assignin('base', ['run_valve_kv_' br{1} '_ts'], seq.run_valve_kv_ts);
end
end
