function [results, P] = ereg_run_case(fluid_name)
%EREG_RUN_CASE Run the standard clean-mode mission sequence with a given fluid.
% OFF -> ARMED (0.5s) -> PRESSURIZE (1s, dead-head) -> RUN (6s, valve open).
here = fileparts(mfilename('fullpath'));
addpath(here, ...
    fullfile(here, '..', 'src', 'controller'), ...
    fullfile(here, '..', 'src', 'plant'), ...
    fullfile(here, '..', 'models'));
P = ereg_params(fluid_name);
P.compat_v1 = false;
P.sequence = { ...
    0.0, 'OFF',        0; ...
    0.5, 'ARMED',      0; ...
    1.0, 'PRESSURIZE', P.Target_Pressure; ...
    6.0, 'RUN',        P.Target_Pressure};
ereg_fanout(P);
results = sim('EReg_v2', 'StopTime', num2str(P.Sim_Duration));
end
